/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DSDataSerialization.proto */

#ifndef PROTOBUF_C_DSDataSerialization_2eproto__INCLUDED
#define PROTOBUF_C_DSDataSerialization_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DSDesignSpaceSerialization__DSMatrix DSDesignSpaceSerialization__DSMatrix;
typedef struct _DSDesignSpaceSerialization__DSSSystem DSDesignSpaceSerialization__DSSSystem;
typedef struct _DSDesignSpaceSerialization__DSCase DSDesignSpaceSerialization__DSCase;


/* --- enums --- */


/* --- messages --- */

struct  _DSDesignSpaceSerialization__DSMatrix
{
  ProtobufCMessage base;
  int32_t rows;
  int32_t columns;
  size_t n_values;
  float *values;
};
#define DSDESIGN_SPACE_SERIALIZATION__DSMATRIX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dsdesign_space_serialization__dsmatrix__descriptor) \
    , 0, 0, 0,NULL }


struct  _DSDesignSpaceSerialization__DSSSystem
{
  ProtobufCMessage base;
  DSDesignSpaceSerialization__DSMatrix *alpha;
  DSDesignSpaceSerialization__DSMatrix *beta;
  DSDesignSpaceSerialization__DSMatrix *gd;
  DSDesignSpaceSerialization__DSMatrix *gi;
  DSDesignSpaceSerialization__DSMatrix *hd;
  DSDesignSpaceSerialization__DSMatrix *hi;
  DSDesignSpaceSerialization__DSMatrix *m;
  protobuf_c_boolean issingular;
  size_t n_xd;
  char **xd;
  size_t n_xd_t;
  char **xd_t;
  size_t n_xd_a;
  char **xd_a;
  size_t n_xi;
  char **xi;
};
#define DSDESIGN_SPACE_SERIALIZATION__DSSSYSTEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dsdesign_space_serialization__dsssystem__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _DSDesignSpaceSerialization__DSCase
{
  ProtobufCMessage base;
  int32_t casenumber;
  DSDesignSpaceSerialization__DSSSystem *ssystem;
  DSDesignSpaceSerialization__DSMatrix *cd;
  DSDesignSpaceSerialization__DSMatrix *ci;
  DSDesignSpaceSerialization__DSMatrix *u;
  DSDesignSpaceSerialization__DSMatrix *delta;
  DSDesignSpaceSerialization__DSMatrix *zeta;
  size_t n_signature;
  int32_t *signature;
};
#define DSDESIGN_SPACE_SERIALIZATION__DSCASE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dsdesign_space_serialization__dscase__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL }


/* DSDesignSpaceSerialization__DSMatrix methods */
void   dsdesign_space_serialization__dsmatrix__init
                     (DSDesignSpaceSerialization__DSMatrix         *message);
size_t dsdesign_space_serialization__dsmatrix__get_packed_size
                     (const DSDesignSpaceSerialization__DSMatrix   *message);
size_t dsdesign_space_serialization__dsmatrix__pack
                     (const DSDesignSpaceSerialization__DSMatrix   *message,
                      uint8_t             *out);
size_t dsdesign_space_serialization__dsmatrix__pack_to_buffer
                     (const DSDesignSpaceSerialization__DSMatrix   *message,
                      ProtobufCBuffer     *buffer);
DSDesignSpaceSerialization__DSMatrix *
       dsdesign_space_serialization__dsmatrix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dsdesign_space_serialization__dsmatrix__free_unpacked
                     (DSDesignSpaceSerialization__DSMatrix *message,
                      ProtobufCAllocator *allocator);
/* DSDesignSpaceSerialization__DSSSystem methods */
void   dsdesign_space_serialization__dsssystem__init
                     (DSDesignSpaceSerialization__DSSSystem         *message);
size_t dsdesign_space_serialization__dsssystem__get_packed_size
                     (const DSDesignSpaceSerialization__DSSSystem   *message);
size_t dsdesign_space_serialization__dsssystem__pack
                     (const DSDesignSpaceSerialization__DSSSystem   *message,
                      uint8_t             *out);
size_t dsdesign_space_serialization__dsssystem__pack_to_buffer
                     (const DSDesignSpaceSerialization__DSSSystem   *message,
                      ProtobufCBuffer     *buffer);
DSDesignSpaceSerialization__DSSSystem *
       dsdesign_space_serialization__dsssystem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dsdesign_space_serialization__dsssystem__free_unpacked
                     (DSDesignSpaceSerialization__DSSSystem *message,
                      ProtobufCAllocator *allocator);
/* DSDesignSpaceSerialization__DSCase methods */
void   dsdesign_space_serialization__dscase__init
                     (DSDesignSpaceSerialization__DSCase         *message);
size_t dsdesign_space_serialization__dscase__get_packed_size
                     (const DSDesignSpaceSerialization__DSCase   *message);
size_t dsdesign_space_serialization__dscase__pack
                     (const DSDesignSpaceSerialization__DSCase   *message,
                      uint8_t             *out);
size_t dsdesign_space_serialization__dscase__pack_to_buffer
                     (const DSDesignSpaceSerialization__DSCase   *message,
                      ProtobufCBuffer     *buffer);
DSDesignSpaceSerialization__DSCase *
       dsdesign_space_serialization__dscase__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dsdesign_space_serialization__dscase__free_unpacked
                     (DSDesignSpaceSerialization__DSCase *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DSDesignSpaceSerialization__DSMatrix_Closure)
                 (const DSDesignSpaceSerialization__DSMatrix *message,
                  void *closure_data);
typedef void (*DSDesignSpaceSerialization__DSSSystem_Closure)
                 (const DSDesignSpaceSerialization__DSSSystem *message,
                  void *closure_data);
typedef void (*DSDesignSpaceSerialization__DSCase_Closure)
                 (const DSDesignSpaceSerialization__DSCase *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dsdesign_space_serialization__dsmatrix__descriptor;
extern const ProtobufCMessageDescriptor dsdesign_space_serialization__dsssystem__descriptor;
extern const ProtobufCMessageDescriptor dsdesign_space_serialization__dscase__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_DSDataSerialization_2eproto__INCLUDED */
