/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DSDataSerialization.proto */

#ifndef PROTOBUF_C_DSDataSerialization_2eproto__INCLUDED
#define PROTOBUF_C_DSDataSerialization_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DSMatrixMessage DSMatrixMessage;
typedef struct _DSSSystemMessage DSSSystemMessage;
typedef struct _DSCaseMessage DSCaseMessage;


/* --- enums --- */


/* --- messages --- */

struct  _DSMatrixMessage
{
  ProtobufCMessage base;
  int32_t rows;
  int32_t columns;
  size_t n_values;
  double *values;
};
#define DSMATRIX_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dsmatrix_message__descriptor) \
    , 0, 0, 0,NULL }


struct  _DSSSystemMessage
{
  ProtobufCMessage base;
  DSMatrixMessage *alpha;
  DSMatrixMessage *beta;
  DSMatrixMessage *gd;
  DSMatrixMessage *gi;
  DSMatrixMessage *hd;
  DSMatrixMessage *hi;
  protobuf_c_boolean issingular;
  DSMatrixMessage *m;
  size_t n_xd;
  char **xd;
  size_t n_xd_t;
  char **xd_t;
  size_t n_xd_a;
  char **xd_a;
  size_t n_xi;
  char **xi;
  DSMatrixMessage *test;
};
#define DSSSYSTEM_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dsssystem_message__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL }


struct  _DSCaseMessage
{
  ProtobufCMessage base;
  int32_t casenumber;
  DSSSystemMessage *ssystem;
  DSMatrixMessage *cd;
  DSMatrixMessage *ci;
  DSMatrixMessage *u;
  DSMatrixMessage *delta;
  DSMatrixMessage *zeta;
  size_t n_signature;
  int32_t *signature;
};
#define DSCASE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dscase_message__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL }


/* DSMatrixMessage methods */
void   dsmatrix_message__init
                     (DSMatrixMessage         *message);
size_t dsmatrix_message__get_packed_size
                     (const DSMatrixMessage   *message);
size_t dsmatrix_message__pack
                     (const DSMatrixMessage   *message,
                      uint8_t             *out);
size_t dsmatrix_message__pack_to_buffer
                     (const DSMatrixMessage   *message,
                      ProtobufCBuffer     *buffer);
DSMatrixMessage *
       dsmatrix_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dsmatrix_message__free_unpacked
                     (DSMatrixMessage *message,
                      ProtobufCAllocator *allocator);
/* DSSSystemMessage methods */
void   dsssystem_message__init
                     (DSSSystemMessage         *message);
size_t dsssystem_message__get_packed_size
                     (const DSSSystemMessage   *message);
size_t dsssystem_message__pack
                     (const DSSSystemMessage   *message,
                      uint8_t             *out);
size_t dsssystem_message__pack_to_buffer
                     (const DSSSystemMessage   *message,
                      ProtobufCBuffer     *buffer);
DSSSystemMessage *
       dsssystem_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dsssystem_message__free_unpacked
                     (DSSSystemMessage *message,
                      ProtobufCAllocator *allocator);
/* DSCaseMessage methods */
void   dscase_message__init
                     (DSCaseMessage         *message);
size_t dscase_message__get_packed_size
                     (const DSCaseMessage   *message);
size_t dscase_message__pack
                     (const DSCaseMessage   *message,
                      uint8_t             *out);
size_t dscase_message__pack_to_buffer
                     (const DSCaseMessage   *message,
                      ProtobufCBuffer     *buffer);
DSCaseMessage *
       dscase_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dscase_message__free_unpacked
                     (DSCaseMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DSMatrixMessage_Closure)
                 (const DSMatrixMessage *message,
                  void *closure_data);
typedef void (*DSSSystemMessage_Closure)
                 (const DSSSystemMessage *message,
                  void *closure_data);
typedef void (*DSCaseMessage_Closure)
                 (const DSCaseMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dsmatrix_message__descriptor;
extern const ProtobufCMessageDescriptor dsssystem_message__descriptor;
extern const ProtobufCMessageDescriptor dscase_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_DSDataSerialization_2eproto__INCLUDED */
