/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DSDataSerialization.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "DSDataSerialization.pb-c.h"
void   dsmatrix_message__init
                     (DSMatrixMessage         *message)
{
  static DSMatrixMessage init_value = DSMATRIX_MESSAGE__INIT;
  *message = init_value;
}
size_t dsmatrix_message__get_packed_size
                     (const DSMatrixMessage *message)
{
  assert(message->base.descriptor == &dsmatrix_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsmatrix_message__pack
                     (const DSMatrixMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsmatrix_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsmatrix_message__pack_to_buffer
                     (const DSMatrixMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsmatrix_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSMatrixMessage *
       dsmatrix_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSMatrixMessage *)
     protobuf_c_message_unpack (&dsmatrix_message__descriptor,
                                allocator, len, data);
}
void   dsmatrix_message__free_unpacked
                     (DSMatrixMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsmatrix_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dsmatrix_array_message__init
                     (DSMatrixArrayMessage         *message)
{
  static DSMatrixArrayMessage init_value = DSMATRIX_ARRAY_MESSAGE__INIT;
  *message = init_value;
}
size_t dsmatrix_array_message__get_packed_size
                     (const DSMatrixArrayMessage *message)
{
  assert(message->base.descriptor == &dsmatrix_array_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsmatrix_array_message__pack
                     (const DSMatrixArrayMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsmatrix_array_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsmatrix_array_message__pack_to_buffer
                     (const DSMatrixArrayMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsmatrix_array_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSMatrixArrayMessage *
       dsmatrix_array_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSMatrixArrayMessage *)
     protobuf_c_message_unpack (&dsmatrix_array_message__descriptor,
                                allocator, len, data);
}
void   dsmatrix_array_message__free_unpacked
                     (DSMatrixArrayMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsmatrix_array_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dsssystem_message__init
                     (DSSSystemMessage         *message)
{
  static DSSSystemMessage init_value = DSSSYSTEM_MESSAGE__INIT;
  *message = init_value;
}
size_t dsssystem_message__get_packed_size
                     (const DSSSystemMessage *message)
{
  assert(message->base.descriptor == &dsssystem_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsssystem_message__pack
                     (const DSSSystemMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsssystem_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsssystem_message__pack_to_buffer
                     (const DSSSystemMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsssystem_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSSSystemMessage *
       dsssystem_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSSSystemMessage *)
     protobuf_c_message_unpack (&dsssystem_message__descriptor,
                                allocator, len, data);
}
void   dsssystem_message__free_unpacked
                     (DSSSystemMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsssystem_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dscase_message__init
                     (DSCaseMessage         *message)
{
  static DSCaseMessage init_value = DSCASE_MESSAGE__INIT;
  *message = init_value;
}
size_t dscase_message__get_packed_size
                     (const DSCaseMessage *message)
{
  assert(message->base.descriptor == &dscase_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dscase_message__pack
                     (const DSCaseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dscase_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dscase_message__pack_to_buffer
                     (const DSCaseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dscase_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSCaseMessage *
       dscase_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSCaseMessage *)
     protobuf_c_message_unpack (&dscase_message__descriptor,
                                allocator, len, data);
}
void   dscase_message__free_unpacked
                     (DSCaseMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dscase_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dscyclical_case_message__init
                     (DSCyclicalCaseMessage         *message)
{
  static DSCyclicalCaseMessage init_value = DSCYCLICAL_CASE_MESSAGE__INIT;
  *message = init_value;
}
size_t dscyclical_case_message__get_packed_size
                     (const DSCyclicalCaseMessage *message)
{
  assert(message->base.descriptor == &dscyclical_case_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dscyclical_case_message__pack
                     (const DSCyclicalCaseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dscyclical_case_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dscyclical_case_message__pack_to_buffer
                     (const DSCyclicalCaseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dscyclical_case_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSCyclicalCaseMessage *
       dscyclical_case_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSCyclicalCaseMessage *)
     protobuf_c_message_unpack (&dscyclical_case_message__descriptor,
                                allocator, len, data);
}
void   dscyclical_case_message__free_unpacked
                     (DSCyclicalCaseMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dscyclical_case_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dsgmasystem_message__init
                     (DSGMASystemMessage         *message)
{
  static DSGMASystemMessage init_value = DSGMASYSTEM_MESSAGE__INIT;
  *message = init_value;
}
size_t dsgmasystem_message__get_packed_size
                     (const DSGMASystemMessage *message)
{
  assert(message->base.descriptor == &dsgmasystem_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsgmasystem_message__pack
                     (const DSGMASystemMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsgmasystem_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsgmasystem_message__pack_to_buffer
                     (const DSGMASystemMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsgmasystem_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSGMASystemMessage *
       dsgmasystem_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSGMASystemMessage *)
     protobuf_c_message_unpack (&dsgmasystem_message__descriptor,
                                allocator, len, data);
}
void   dsgmasystem_message__free_unpacked
                     (DSGMASystemMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsgmasystem_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dsdesign_space_message__init
                     (DSDesignSpaceMessage         *message)
{
  static DSDesignSpaceMessage init_value = DSDESIGN_SPACE_MESSAGE__INIT;
  *message = init_value;
}
size_t dsdesign_space_message__get_packed_size
                     (const DSDesignSpaceMessage *message)
{
  assert(message->base.descriptor == &dsdesign_space_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsdesign_space_message__pack
                     (const DSDesignSpaceMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsdesign_space_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsdesign_space_message__pack_to_buffer
                     (const DSDesignSpaceMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsdesign_space_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSDesignSpaceMessage *
       dsdesign_space_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSDesignSpaceMessage *)
     protobuf_c_message_unpack (&dsdesign_space_message__descriptor,
                                allocator, len, data);
}
void   dsdesign_space_message__free_unpacked
                     (DSDesignSpaceMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsdesign_space_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dsmatrix_message__field_descriptors[3] =
{
  {
    "rows",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DSMatrixMessage, rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "columns",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DSMatrixMessage, columns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(DSMatrixMessage, n_values),
    offsetof(DSMatrixMessage, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsmatrix_message__field_indices_by_name[] = {
  1,   /* field[1] = columns */
  0,   /* field[0] = rows */
  2,   /* field[2] = values */
};
static const ProtobufCIntRange dsmatrix_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dsmatrix_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSMatrixMessage",
  "DSMatrixMessage",
  "DSMatrixMessage",
  "",
  sizeof(DSMatrixMessage),
  3,
  dsmatrix_message__field_descriptors,
  dsmatrix_message__field_indices_by_name,
  1,  dsmatrix_message__number_ranges,
  (ProtobufCMessageInit) dsmatrix_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dsmatrix_array_message__field_descriptors[1] =
{
  {
    "matrices",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DSMatrixArrayMessage, n_matrices),
    offsetof(DSMatrixArrayMessage, matrices),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsmatrix_array_message__field_indices_by_name[] = {
  0,   /* field[0] = matrices */
};
static const ProtobufCIntRange dsmatrix_array_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dsmatrix_array_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSMatrixArrayMessage",
  "DSMatrixArrayMessage",
  "DSMatrixArrayMessage",
  "",
  sizeof(DSMatrixArrayMessage),
  1,
  dsmatrix_array_message__field_descriptors,
  dsmatrix_array_message__field_indices_by_name,
  1,  dsmatrix_array_message__number_ranges,
  (ProtobufCMessageInit) dsmatrix_array_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dsssystem_message__field_descriptors[12] =
{
  {
    "alpha",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, alpha),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beta",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, beta),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, gd),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gi",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, gi),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Hd",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, hd),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Hi",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, hi),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isSingular",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, issingular),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "M",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSSSystemMessage, m),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSSSystemMessage, n_xd),
    offsetof(DSSSystemMessage, xd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd_t",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSSSystemMessage, n_xd_t),
    offsetof(DSSSystemMessage, xd_t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd_a",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSSSystemMessage, n_xd_a),
    offsetof(DSSSystemMessage, xd_a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xi",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSSSystemMessage, n_xi),
    offsetof(DSSSystemMessage, xi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsssystem_message__field_indices_by_name[] = {
  2,   /* field[2] = Gd */
  3,   /* field[3] = Gi */
  4,   /* field[4] = Hd */
  5,   /* field[5] = Hi */
  7,   /* field[7] = M */
  8,   /* field[8] = Xd */
  10,   /* field[10] = Xd_a */
  9,   /* field[9] = Xd_t */
  11,   /* field[11] = Xi */
  0,   /* field[0] = alpha */
  1,   /* field[1] = beta */
  6,   /* field[6] = isSingular */
};
static const ProtobufCIntRange dsssystem_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor dsssystem_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSSSystemMessage",
  "DSSSystemMessage",
  "DSSSystemMessage",
  "",
  sizeof(DSSSystemMessage),
  12,
  dsssystem_message__field_descriptors,
  dsssystem_message__field_indices_by_name,
  1,  dsssystem_message__number_ranges,
  (ProtobufCMessageInit) dsssystem_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dscase_message__field_descriptors[8] =
{
  {
    "caseNumber",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DSCaseMessage, casenumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssystem",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCaseMessage, ssystem),
    &dsssystem_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Cd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCaseMessage, cd),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ci",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCaseMessage, ci),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DSCaseMessage, n_signature),
    offsetof(DSCaseMessage, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "U",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCaseMessage, u),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCaseMessage, delta),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zeta",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCaseMessage, zeta),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dscase_message__field_indices_by_name[] = {
  2,   /* field[2] = Cd */
  3,   /* field[3] = Ci */
  5,   /* field[5] = U */
  0,   /* field[0] = caseNumber */
  6,   /* field[6] = delta */
  4,   /* field[4] = signature */
  1,   /* field[1] = ssystem */
  7,   /* field[7] = zeta */
};
static const ProtobufCIntRange dscase_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor dscase_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSCaseMessage",
  "DSCaseMessage",
  "DSCaseMessage",
  "",
  sizeof(DSCaseMessage),
  8,
  dscase_message__field_descriptors,
  dscase_message__field_indices_by_name,
  1,  dscase_message__number_ranges,
  (ProtobufCMessageInit) dscase_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dscyclical_case_message__field_descriptors[2] =
{
  {
    "originalCase",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCyclicalCaseMessage, originalcase),
    &dscase_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "internalDesignspace",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSCyclicalCaseMessage, internaldesignspace),
    &dsdesign_space_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dscyclical_case_message__field_indices_by_name[] = {
  1,   /* field[1] = internalDesignspace */
  0,   /* field[0] = originalCase */
};
static const ProtobufCIntRange dscyclical_case_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dscyclical_case_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSCyclicalCaseMessage",
  "DSCyclicalCaseMessage",
  "DSCyclicalCaseMessage",
  "",
  sizeof(DSCyclicalCaseMessage),
  2,
  dscyclical_case_message__field_descriptors,
  dscyclical_case_message__field_indices_by_name,
  1,  dscyclical_case_message__number_ranges,
  (ProtobufCMessageInit) dscyclical_case_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dsgmasystem_message__field_descriptors[11] =
{
  {
    "alpha",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSGMASystemMessage, alpha),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beta",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSGMASystemMessage, beta),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSGMASystemMessage, gd),
    &dsmatrix_array_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gi",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSGMASystemMessage, gi),
    &dsmatrix_array_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Hd",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSGMASystemMessage, hd),
    &dsmatrix_array_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Hi",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSGMASystemMessage, hi),
    &dsmatrix_array_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSGMASystemMessage, n_xd),
    offsetof(DSGMASystemMessage, xd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd_a",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSGMASystemMessage, n_xd_a),
    offsetof(DSGMASystemMessage, xd_a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd_t",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSGMASystemMessage, n_xd_t),
    offsetof(DSGMASystemMessage, xd_t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xi",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSGMASystemMessage, n_xi),
    offsetof(DSGMASystemMessage, xi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DSGMASystemMessage, n_signature),
    offsetof(DSGMASystemMessage, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsgmasystem_message__field_indices_by_name[] = {
  2,   /* field[2] = Gd */
  3,   /* field[3] = Gi */
  4,   /* field[4] = Hd */
  5,   /* field[5] = Hi */
  6,   /* field[6] = Xd */
  7,   /* field[7] = Xd_a */
  8,   /* field[8] = Xd_t */
  9,   /* field[9] = Xi */
  0,   /* field[0] = alpha */
  1,   /* field[1] = beta */
  10,   /* field[10] = signature */
};
static const ProtobufCIntRange dsgmasystem_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor dsgmasystem_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSGMASystemMessage",
  "DSGMASystemMessage",
  "DSGMASystemMessage",
  "",
  sizeof(DSGMASystemMessage),
  11,
  dsgmasystem_message__field_descriptors,
  dsgmasystem_message__field_indices_by_name,
  1,  dsgmasystem_message__number_ranges,
  (ProtobufCMessageInit) dsgmasystem_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dsdesign_space_message__field_descriptors[6] =
{
  {
    "gma",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceMessage, gma),
    &dsgmasystem_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Cd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceMessage, cd),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ci",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceMessage, ci),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceMessage, delta),
    &dsmatrix_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seriesCalculations",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceMessage, seriescalculations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "validCases",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DSDesignSpaceMessage, n_validcases),
    offsetof(DSDesignSpaceMessage, validcases),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsdesign_space_message__field_indices_by_name[] = {
  1,   /* field[1] = Cd */
  2,   /* field[2] = Ci */
  3,   /* field[3] = delta */
  0,   /* field[0] = gma */
  4,   /* field[4] = seriesCalculations */
  5,   /* field[5] = validCases */
};
static const ProtobufCIntRange dsdesign_space_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor dsdesign_space_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSDesignSpaceMessage",
  "DSDesignSpaceMessage",
  "DSDesignSpaceMessage",
  "",
  sizeof(DSDesignSpaceMessage),
  6,
  dsdesign_space_message__field_descriptors,
  dsdesign_space_message__field_indices_by_name,
  1,  dsdesign_space_message__number_ranges,
  (ProtobufCMessageInit) dsdesign_space_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
