/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DSDataSerialization.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "DSDataSerialization.pb-c.h"
void   dsdesign_space_serialization__dsmatrix__init
                     (DSDesignSpaceSerialization__DSMatrix         *message)
{
  static DSDesignSpaceSerialization__DSMatrix init_value = DSDESIGN_SPACE_SERIALIZATION__DSMATRIX__INIT;
  *message = init_value;
}
size_t dsdesign_space_serialization__dsmatrix__get_packed_size
                     (const DSDesignSpaceSerialization__DSMatrix *message)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsmatrix__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsdesign_space_serialization__dsmatrix__pack
                     (const DSDesignSpaceSerialization__DSMatrix *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsmatrix__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsdesign_space_serialization__dsmatrix__pack_to_buffer
                     (const DSDesignSpaceSerialization__DSMatrix *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsmatrix__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSDesignSpaceSerialization__DSMatrix *
       dsdesign_space_serialization__dsmatrix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSDesignSpaceSerialization__DSMatrix *)
     protobuf_c_message_unpack (&dsdesign_space_serialization__dsmatrix__descriptor,
                                allocator, len, data);
}
void   dsdesign_space_serialization__dsmatrix__free_unpacked
                     (DSDesignSpaceSerialization__DSMatrix *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsmatrix__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dsdesign_space_serialization__dsssystem__init
                     (DSDesignSpaceSerialization__DSSSystem         *message)
{
  static DSDesignSpaceSerialization__DSSSystem init_value = DSDESIGN_SPACE_SERIALIZATION__DSSSYSTEM__INIT;
  *message = init_value;
}
size_t dsdesign_space_serialization__dsssystem__get_packed_size
                     (const DSDesignSpaceSerialization__DSSSystem *message)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsssystem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsdesign_space_serialization__dsssystem__pack
                     (const DSDesignSpaceSerialization__DSSSystem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsssystem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsdesign_space_serialization__dsssystem__pack_to_buffer
                     (const DSDesignSpaceSerialization__DSSSystem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsssystem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSDesignSpaceSerialization__DSSSystem *
       dsdesign_space_serialization__dsssystem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSDesignSpaceSerialization__DSSSystem *)
     protobuf_c_message_unpack (&dsdesign_space_serialization__dsssystem__descriptor,
                                allocator, len, data);
}
void   dsdesign_space_serialization__dsssystem__free_unpacked
                     (DSDesignSpaceSerialization__DSSSystem *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dsssystem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dsdesign_space_serialization__dscase__init
                     (DSDesignSpaceSerialization__DSCase         *message)
{
  static DSDesignSpaceSerialization__DSCase init_value = DSDESIGN_SPACE_SERIALIZATION__DSCASE__INIT;
  *message = init_value;
}
size_t dsdesign_space_serialization__dscase__get_packed_size
                     (const DSDesignSpaceSerialization__DSCase *message)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dscase__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dsdesign_space_serialization__dscase__pack
                     (const DSDesignSpaceSerialization__DSCase *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dscase__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dsdesign_space_serialization__dscase__pack_to_buffer
                     (const DSDesignSpaceSerialization__DSCase *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dscase__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DSDesignSpaceSerialization__DSCase *
       dsdesign_space_serialization__dscase__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DSDesignSpaceSerialization__DSCase *)
     protobuf_c_message_unpack (&dsdesign_space_serialization__dscase__descriptor,
                                allocator, len, data);
}
void   dsdesign_space_serialization__dscase__free_unpacked
                     (DSDesignSpaceSerialization__DSCase *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dsdesign_space_serialization__dscase__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dsdesign_space_serialization__dsmatrix__field_descriptors[3] =
{
  {
    "rows",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSMatrix, rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "columns",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSMatrix, columns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DSDesignSpaceSerialization__DSMatrix, n_values),
    offsetof(DSDesignSpaceSerialization__DSMatrix, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsdesign_space_serialization__dsmatrix__field_indices_by_name[] = {
  1,   /* field[1] = columns */
  0,   /* field[0] = rows */
  2,   /* field[2] = values */
};
static const ProtobufCIntRange dsdesign_space_serialization__dsmatrix__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dsdesign_space_serialization__dsmatrix__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSDesignSpaceSerialization.DSMatrix",
  "DSMatrix",
  "DSDesignSpaceSerialization__DSMatrix",
  "DSDesignSpaceSerialization",
  sizeof(DSDesignSpaceSerialization__DSMatrix),
  3,
  dsdesign_space_serialization__dsmatrix__field_descriptors,
  dsdesign_space_serialization__dsmatrix__field_indices_by_name,
  1,  dsdesign_space_serialization__dsmatrix__number_ranges,
  (ProtobufCMessageInit) dsdesign_space_serialization__dsmatrix__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dsdesign_space_serialization__dsssystem__field_descriptors[12] =
{
  {
    "alpha",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, alpha),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beta",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, beta),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, gd),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Gi",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, gi),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Hd",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, hd),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Hi",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, hi),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "M",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, m),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isSingular",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSSSystem, issingular),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSDesignSpaceSerialization__DSSSystem, n_xd),
    offsetof(DSDesignSpaceSerialization__DSSSystem, xd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd_t",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSDesignSpaceSerialization__DSSSystem, n_xd_t),
    offsetof(DSDesignSpaceSerialization__DSSSystem, xd_t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xd_a",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSDesignSpaceSerialization__DSSSystem, n_xd_a),
    offsetof(DSDesignSpaceSerialization__DSSSystem, xd_a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Xi",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DSDesignSpaceSerialization__DSSSystem, n_xi),
    offsetof(DSDesignSpaceSerialization__DSSSystem, xi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsdesign_space_serialization__dsssystem__field_indices_by_name[] = {
  2,   /* field[2] = Gd */
  3,   /* field[3] = Gi */
  4,   /* field[4] = Hd */
  5,   /* field[5] = Hi */
  6,   /* field[6] = M */
  8,   /* field[8] = Xd */
  10,   /* field[10] = Xd_a */
  9,   /* field[9] = Xd_t */
  11,   /* field[11] = Xi */
  0,   /* field[0] = alpha */
  1,   /* field[1] = beta */
  7,   /* field[7] = isSingular */
};
static const ProtobufCIntRange dsdesign_space_serialization__dsssystem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor dsdesign_space_serialization__dsssystem__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSDesignSpaceSerialization.DSSSystem",
  "DSSSystem",
  "DSDesignSpaceSerialization__DSSSystem",
  "DSDesignSpaceSerialization",
  sizeof(DSDesignSpaceSerialization__DSSSystem),
  12,
  dsdesign_space_serialization__dsssystem__field_descriptors,
  dsdesign_space_serialization__dsssystem__field_indices_by_name,
  1,  dsdesign_space_serialization__dsssystem__number_ranges,
  (ProtobufCMessageInit) dsdesign_space_serialization__dsssystem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dsdesign_space_serialization__dscase__field_descriptors[8] =
{
  {
    "caseNumber",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSCase, casenumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssystem",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSCase, ssystem),
    &dsdesign_space_serialization__dsssystem__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Cd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSCase, cd),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ci",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSCase, ci),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "U",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSCase, u),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSCase, delta),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zeta",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DSDesignSpaceSerialization__DSCase, zeta),
    &dsdesign_space_serialization__dsmatrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DSDesignSpaceSerialization__DSCase, n_signature),
    offsetof(DSDesignSpaceSerialization__DSCase, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dsdesign_space_serialization__dscase__field_indices_by_name[] = {
  2,   /* field[2] = Cd */
  3,   /* field[3] = Ci */
  4,   /* field[4] = U */
  0,   /* field[0] = caseNumber */
  5,   /* field[5] = delta */
  7,   /* field[7] = signature */
  1,   /* field[1] = ssystem */
  6,   /* field[6] = zeta */
};
static const ProtobufCIntRange dsdesign_space_serialization__dscase__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor dsdesign_space_serialization__dscase__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DSDesignSpaceSerialization.DSCase",
  "DSCase",
  "DSDesignSpaceSerialization__DSCase",
  "DSDesignSpaceSerialization",
  sizeof(DSDesignSpaceSerialization__DSCase),
  8,
  dsdesign_space_serialization__dscase__field_descriptors,
  dsdesign_space_serialization__dscase__field_indices_by_name,
  1,  dsdesign_space_serialization__dscase__number_ranges,
  (ProtobufCMessageInit) dsdesign_space_serialization__dscase__init,
  NULL,NULL,NULL    /* reserved[123] */
};
